export const memoryStore = {
  profile: {
    eyebrow: 'Full-Stack Developer & Code Architect',
    title1: 'CODE',
    titleAccent: 'IN THE',
    title2: 'SHADOWS',
    subtext: 'Full-stack engineer & open-source developer. I build scalable backend systems, craft pixel-perfect interfaces, and write clean, high-performance code.',
    projectsShipped: '15+',
    yearsCoding: '3+',
    clientsServed: '500+',
    status: 'Open to Opportunities',
    statusDetail: 'Available for Full-Stack & Software Engineering roles. Focused on building high-performance web applications and backend systems.',
    email: 'kumarharsh1851@gmail.com',
    pgpKey: 'github.com/harsh24239',
  },
  projects: [
    {
      _id: '1',
      title: 'ShadowBoard',
      tag: 'Full-Stack — SaaS',
      description: 'A real-time project management SaaS built with Next.js, Supabase, and WebSockets. 10K+ active users, 99.9% uptime, deployed on AWS with zero-downtime CI/CD pipeline.',
      year: '2025',
      link: '',
      iconText: 'SB',
      featured: true,
      sortOrder: 0,
    },
    {
      _id: '2',
      title: 'KageUI',
      tag: 'React — TypeScript',
      description: 'Open-source component library with 40+ dark-themed UI components. 2.3K GitHub stars, full TypeScript support, Storybook docs.',
      year: '2025',
      link: '',
      iconText: 'KU',
      featured: false,
      sortOrder: 1,
    },
    {
      _id: '3',
      title: 'NinjaBot',
      tag: 'Python — AI',
      description: 'LLM-powered code review bot that integrates with GitHub PRs. Catches bugs, suggests refactors, enforces style guides. 94% accuracy on test suite.',
      year: '2024',
      link: '',
      iconText: 'NB',
      featured: false,
      sortOrder: 2,
    },
    {
      _id: '4',
      title: 'StealthAPI',
      tag: 'Go — Microservices',
      description: 'High-performance REST API gateway in Go handling 1M+ requests/day. Rate limiting, JWT auth, Redis caching, Kubernetes orchestration.',
      year: '2024',
      link: '',
      iconText: 'SA',
      featured: false,
      sortOrder: 3,
    },
  ],
  skills: [
    { _id: '1', name: 'Frontend Mastery', desc: 'React, Next.js, TypeScript, Tailwind CSS. Pixel-perfect UIs that load fast and feel alive.', pips: 5 },
    { _id: '2', name: 'Backend Engineering', desc: 'Node.js, Express, Python, REST & GraphQL APIs. Scalable server architecture built to endure.', pips: 5 },
    { _id: '3', name: 'Database & Cloud', desc: 'PostgreSQL, MongoDB, Redis, AWS, Docker. Data infrastructure built for speed.', pips: 4 },
    { _id: '4', name: 'DevOps & CI/CD', desc: 'GitHub Actions, Linux, Docker, Vercel, Render. Automated pipelines that deploy without friction.', pips: 4 },
    { _id: '5', name: 'Security & Auth', desc: 'OAuth2, JWT, bcrypt encryption, OWASP hardening. Code that guards itself like a fortress.', pips: 5 },
    { _id: '6', name: 'AI & Automation', desc: 'LLM API integration, Python automation, web scraping, data pipelines. Smart systems built for scale.', pips: 4 },
  ],
  testimonials: [
    {
      _id: '1',
      quote: 'Harsh delivered clean, maintainable architecture under tight deadlines. His understanding of full-stack systems is exceptional.',
      name: 'Marcus Reyes',
      role: 'Lead Architect',
      org: 'Software Engineering',
    },
    {
      _id: '2',
      quote: 'The design system and component library built for our project surpassed all expectations. Fast, responsive, and beautifully crafted.',
      name: 'Yuki Tanaka',
      role: 'Product Lead',
      org: 'Tech Innovations',
    },
    {
      _id: '3',
      quote: 'The real-time data pipeline has been running seamlessly without downtime. Highly technical, dedicated, and thorough engineer.',
      name: 'Kwame Osei',
      role: 'Engineering Manager',
      org: 'Cloud Solutions',
    },
    {
      _id: '4',
      quote: 'Outstanding work ethic and problem-solving ability. Delivered modular code with zero friction.',
      name: 'Dmitri Volkov',
      role: 'Senior Engineer',
      org: 'Dev Systems',
    },
  ],
  messages: [],
};
