export const memoryStore = {
  profile: {
    eyebrow: 'WEB DEVELOPER & AI BUILDER',
    title1: 'CODE',
    titleAccent: 'IN THE',
    title2: 'SHADOWS',
    subtext: '3rd-Year Computer Science B.Tech student & Web Developer. I build clean web applications, integrate intelligent AI workflows, and solve complex DSA problems.',
    projectsShipped: '15+',
    yearsCoding: '3+',
    clientsServed: '500+',
    status: 'Available for Web Dev & Software Roles',
    statusDetail: 'Focused on Web Development & AI Applications. Actively building projects with React, Node.js, Express, FastAPI, and LangGraph.',
    email: 'kumarharsh1851@gmail.com',
    pgpKey: 'github.com/harsh24239',
  },
  projects: [
    {
      _id: '1',
      title: 'AI Placement Copilot',
      tag: 'FastAPI — LangGraph — AI',
      description: 'Agentic AI-powered placement preparation platform using LangGraph, FastAPI, React, and RAG vector retrieval with ChromaDB & Gemini embeddings.',
      year: '2026 (Ongoing)',
      link: 'https://github.com/harsh24239/ai-placement-copilot',
      iconText: 'AI',
      featured: true,
      sortOrder: 0,
    },
    {
      _id: '2',
      title: 'VR Manual Milling Simulator',
      tag: 'Unity / C# — VR Simulation',
      description: 'VR manual milling trainer prototype — Blender + Unity/C# simulation with force-based haptic feedback. Research-aligned XR hardware/software project.',
      year: '2026 (In Progress)',
      link: 'https://github.com/harsh24239/vr-manual-milling-simulator',
      iconText: 'VR',
      featured: false,
      sortOrder: 1,
    },
    {
      _id: '3',
      title: 'SQVS – Student Qualification Verification',
      tag: 'React — Node.js — MySQL — DBMS',
      description: 'Full-stack credential verification web application developed as a Database Systems project. Features RBAC auth, analytics dashboards, audit logs, and RESTful Express APIs on a normalized MySQL schema.',
      year: '2026',
      link: 'https://github.com/harsh24239',
      iconText: 'SQ',
      featured: false,
      sortOrder: 2,
    },
    {
      _id: '4',
      title: 'University ERP System',
      tag: 'Java — Swing & JDBC — Systems',
      description: 'Role-based desktop ERP application built in Java with a 4-layer architecture (UI, API, Service, DAO). Features BCrypt authentication, deadline-enforced grade management, and JUnit automated unit tests.',
      year: '2025',
      link: 'https://github.com/harsh24239',
      iconText: 'UE',
      featured: false,
      sortOrder: 3,
    },
  ],
  skills: [
    { _id: '1', name: 'Web Development', desc: 'HTML5, CSS3, JavaScript, React.js, Vite, Node.js, Express.js. Building responsive web UIs & REST APIs.', pips: 5 },
    { _id: '2', name: 'AI & Automation', desc: 'LangGraph, FastAPI, ChromaDB, RAG Vector Retrieval, Gemini API, Multi-Agent Workflows.', pips: 5 },
    { _id: '3', name: 'Core Languages & DSA', desc: 'Python, Java, C, SQL. Data Structures, Algorithms, Object-Oriented Programming (OOP).', pips: 5 },
    { _id: '4', name: 'Database Systems', desc: 'MySQL, SQLite, SQLAlchemy, DBMS, Schema Normalization, Relational Modeling, JDBC.', pips: 4 },
    { _id: '5', name: 'Security & Testing', desc: 'RBAC Auth, BCrypt Password Hashing, JWT Tokens, JUnit Automated Unit Testing.', pips: 4 },
    { _id: '6', name: 'Developer Tools & OS', desc: 'Git, GitHub, Linux/Unix Shell, Postman, VS Code, IntelliJ IDEA, Operating Systems.', pips: 5 },
  ],
  focusAreas: [
    {
      _id: '1',
      tag: 'WEB DEVELOPMENT',
      title: 'Responsive Web Applications',
      desc: 'Building modern, clean, and responsive web interfaces using React.js, Vite, Node.js, Express.js, and RESTful APIs.',
    },
    {
      _id: '2',
      tag: 'AI & AUTOMATION',
      title: 'AI Workflows & RAG',
      desc: 'Integrating autonomous multi-agent pipelines using LangGraph, ChromaDB vector retrieval, RAG, and FastAPI.',
    },
    {
      _id: '3',
      tag: 'CORE CS & DSA',
      title: 'Algorithmic Problem Solving',
      desc: '3rd-Year Computer Science B.Tech student actively solving Data Structures and Algorithms problems in Python, Java, and C.',
    },
    {
      _id: '4',
      tag: 'SOFTWARE CRAFT',
      title: 'Clean Architecture & Security',
      desc: 'Applying 4-layer system design, MVC architecture, BCrypt password security, role-based access control (RBAC), and automated unit testing.',
    },
  ],
  messages: [],
};
